#!/bin/bash

# arguments
# $1 servername

image="artifactory.eur.gad.schneider-electric.com:8888/ubuntu:focal-20220531"

DB_VOLUME="$1-db"
DB_FOLDER="/var/sbo"

docker run --rm --mount source=$DB_VOLUME,target=$DB_FOLDER $image ls /var/sbo/db_backup/LocalBackup
