#!/bin/bash

# arguments
# $1 servername

image="ubuntu:focal"

DB_VOLUME="$1-db"
DB_FOLDER="/var/sbo"

docker run --rm --mount source=$DB_VOLUME,target=$DB_FOLDER $image ls /var/sbo/db_backup/LocalBackup
