#!/bin/bash

# arguments
# $1 servername
# $2 version


DB_VOLUME="$1-db"
VERSION=$2

image="artifactory.eur.gad.schneider-electric.com:8888/ebo/ebo-edge-server:$VERSION"
DB_FOLDER="/var/sbo"

echo "Starting container..."
docker run --rm --mount source=$DB_VOLUME,target=$DB_FOLDER $image bash -c "mkdir -p /var/sbo/db/reset && touch /var/sbo/db/reset/r0.txt"
